version: "3.8"

services:
  skurczybyk:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:14
    env_file:
      - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    container_name: web
    image: ghcr.io/nico-industries/site:main
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - db
    restart: unless-stopped
